---
- name: Deploy Docker container to target servers
  hosts: targets
  tasks:
    - name: Stop and remove existing container
      command: docker rm -f myapp
      become: yes 
      ignore_errors: yes  

    - name: Remove old Docker image
      command: docker rmi alpaslant/myapp:latest
      become: yes
      ignore_errors: yes

    - name: Pull Docker image from Docker Hub
      command: docker pull alpaslant/myapp:latest
      become: yes

    - name: Run Docker container
      command: docker run -d --name myapp -p 5000:5000 --restart always alpaslant/myapp:latest
      become: yes