---
- name: Deploy Docker container to target servers
  hosts: targets
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes
      become: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Pull Docker image from Docker Hub
      docker_image:
        name: "alpaslant/myapp:latest"
        source: pull
      become: yes

    - name: Run Docker container
      docker_container:
        name: myapp
        image: "alpaslant/myapp:latest"
        state: started
        restart_policy: always
        ports:
          - "5000:5000"
      become: yes